name: Secrets Scanning with Gitleaks

on:
  push:
    branches:
      - master # Run on push to the master branch
  pull_request:
    branches:
      - master  # Run on pull request targeting the master branch

jobs:
  gitleaks:
    name: Secrets Scanning (Gitleaks)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          args: detect --redact --verbose
