name: SCA with Snyk

on:
  push:
    branches:
      - master  # Run on push to the main branch
  pull_request:
    branches:
      - master  # Run on pull request targeting the main branch

jobs:
  snyk:
    name: Software Composition Analysis with Snyk
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.19.1'

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Run Snyk Test
        run: snyk test --all-projects --json > snyk-report.json

      - name: Upload Snyk report
        uses: actions/upload-artifact@v2
        with:
          name: snyk-report
          path: snyk-report.json
