name: SCA Snyk Scan

on:
  push:
    branches:
      - main  # Trigger on push to the main branch (can modify based on your workflow)
  pull_request:
    branches:
      - main  # Trigger on PR targeting the main branch

jobs:
  snyk:
    name: Software Composition Analysis (SCA) with Snyk
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js v18.19.1
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.19.1'  # Specify your Node.js version here

      # Step 3: Install project dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Install Snyk CLI
      - name: Install Snyk CLI
        run: npm install -g snyk

      # Step 5: Run Snyk Test
      - name: Run Snyk Test
        run: snyk test --all-projects --json > snyk-report.json

      # Step 6: Upload Snyk report as artifact
      - name: Upload Snyk report
        uses: actions/upload-artifact@v2
        with:
          name: snyk-report
          path: snyk-report.json  # Save the Snyk test report as an artifact
